# This is an autogenerated file. Do not edit this file directly.

provider "docker" {
  host = "unix:///var/run/docker.sock"
}

resource "docker_container" "zzz" {
  image = "redis:latest"
  name = "zzz"
}