# This is an autogenerated file. Do not edit this file directly.

terraform {
  required_version = ">= 0.13"
}

provider "docker" {
  host = "unix:///var/run/docker.sock"
}

resource "docker_container" "foo" {
  image = var.image
  name  = "foo"
}

module "module_a" {
  source = "./module_a"
}