# This is an autogenerated file. Do not edit this file directly.

output "container_foo_id" {
  value = docker_container.foo.id
}

output "container_bar_id" {
  value = module.module_a.container_bar_id
}