# This is an autogenerated file. Do not edit this file directly.

variable "image" {
  type    = string
  default = "redis"
}

variable "test_variable" {
  type = list(object({ one = number, two = number }))
  default = [
    {
      one = 1
      two = 2
    }
  ]
}