# This is an autogenerated file. Do not edit this file directly.

provider "docker" {
  host = "unix:///var/run/docker.sock"
}

resource "docker_container" "bar" {
  image = "redis:latest"
  name = "bar"
}

module "module_b" {
  source = "./module_b"
}